--1.1P
DROP TABLE A2ERROREVENT;
/

create table A2ERROREVENT (
ERRORID INTEGER,
SOURCE_ROWID ROWID,
SOURCE_TABLE VARCHAR2(30),
FILTERID INTEGER,
DATETIME DATE,
ACTION VARCHAR2(6),
CONSTRAINT ERROREVENTACTION
CHECK (ACTION IN ('SKIP','MODIFY'))
);
/

create sequence erroridseq;
/

DROP TABLE DWPROD;
/

create table DWPROD(
DWPRODID number, 
DWSOURCETABLE varchar2(40), 
DWSOURCEID number, 
PRODNAME varchar2(40), 
PRODCATNAME varchar2(40), 
PRODMANUNAME varchar2(40),
PRODSHIPNAME varchar2(40));
/

CREATE SEQUENCE DWPRODSEQ;
/

DROP TABLE DWCUST;
/

create table DWCUST (DWCUSTID number, 
DWSOURCEIDBRIS number NOT NULL, 
DWSOURCEIDMELB number, 
FIRSTNAME varchar2(40), 
SURNAME varchar2(40), 
GENDER varchar2(40), 
PHONE varchar2(40),
POSTCODE varchar2(40), 
CITY varchar2(40),  
STATE varchar2(40), 
CUSTCATNAME varchar(40));
/

CREATE SEQUENCE DWCUSTSEQ;
/

DROP TABLE DWSALE;
/

create table DWSALE (DWSALEID number, 
DWCUSTID number, 
DWPRODID number, 
DWSOURCEIDBRIS number, 
DWSOURCEIDMELB number, 
QTY number,
SALE_DWDATEID number, 
SHIP_DWDATEID number, 
SALEPRICE number);
/

CREATE SEQUENCE DWSALESEQ;
/

create table GENDERSPELLING(Invalid_Value varchar2(40), 
New_Value varchar2(40));
/

insert into GENDERSPELLING(Invalid_Value,New_Value) values('MAIL','M');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('WOMAN','F');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('FEM','F');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('FEMALE','F');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('MALE','M');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('GENTLEMAN','M');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('MM','M');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('FF','F');
insert into GENDERSPELLING(Invalid_Value,New_Value) values('FEMAIL','F');
/

--2.1
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
 select erroridseq.nextval,ROWID,'A2PRODUCT',1,sysdate,'SKIP'
 from A2PRODUCT AP
 where AP.PRODNAME is null;
/

--2.2
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
 select erroridseq.nextval,ROWID,'A2PRODUCT',2,sysdate,'MODIFY'
 from A2PRODUCT AP
 where AP.MANUFACTURERCODE is null;
/

 --2.3
 insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
 select erroridseq.nextval,ROWID,'A2PRODUCT',3,sysdate,'MODIFY'
 from A2PRODUCT AP
 where AP.PRODCATEGORY is null
 or AP.PRODCATEGORY not in(select AC.PRODUCTCATEGORY from A2PRODCATEGORY AC) ;
/
 
 --2.4.3
 
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE,DWSOURCEID,PRODNAME,PRODCATNAME,PRODMANUNAME,PRODSHIPNAME)
SELECT DWPRODSEQ.NEXTVAL,'A2PRODUCT',AP.PRODID,AP.PRODNAME,AC.CATEGORYNAME,AM.MANUNAME,AH.DESCRIPTION
FROM A2PRODUCT AP ,
      A2MANUFACTURER AM,
      A2SHIPPING AH,
      a2PRODCATEGORY AC
where AP.PRODCATEGORY = AC.PRODUCTCATEGORY
 AND   AP.MANUFACTURERCODE = AM.MANUCODE
 AND   AP.SHIPPINGCODE = AH.SHIPPINGCODE
 AND   AP.ROWID NOT IN(SELECT SOURCE_ROWID FROM A2ERROREVENT);
/

--2.4.4
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE,DWSOURCEID,PRODNAME,PRODCATNAME,PRODMANUNAME,PRODSHIPNAME)
SELECT DWPRODSEQ.NEXTVAL,'A2PRODUCT',AP.PRODID,AP.PRODNAME,AC.CATEGORYNAME,'UNKNOWN',AH.DESCRIPTION
FROM A2PRODUCT AP ,
      --A2MANUFACTURER AM,
      A2SHIPPING AH,
      a2PRODCATEGORY AC
where AP.PRODCATEGORY = AC.PRODUCTCATEGORY
-- AND   AP.MANUFACTURERCODE = AM.MANUCODE
 AND   AP.SHIPPINGCODE = AH.SHIPPINGCODE 
 AND AP.MANUFACTURERCODE IS NULL
 AND  AP.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 2 AND ACTION = 'MODIFY');
 /
 
 --2.4.5
INSERT INTO DWPROD (DWPRODID, DWSOURCETABLE,DWSOURCEID,PRODNAME,PRODCATNAME,PRODMANUNAME,PRODSHIPNAME)
SELECT DWPRODSEQ.NEXTVAL,'A2PRODUCT',AP.PRODID,AP.PRODNAME,'UNKNOWN',AM.MANUNAME,AH.DESCRIPTION
FROM A2PRODUCT AP ,
      A2MANUFACTURER AM,
      A2SHIPPING AH
      --a2PRODCATEGORY AC
where --AP.PRODCATEGORY = AC.PRODUCTCATEGORY
    AP.MANUFACTURERCODE = AM.MANUCODE
 AND   AP.SHIPPINGCODE = AH.SHIPPINGCODE
 AND   AP.ROWID IN(SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 3 AND ACTION = 'MODIFY' );
 /

 
--3.1
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2CUSTBRIS',4,sysdate,'MODIFY'
FROM A2CUSTBRIS AB
WHERE AB.CUSTCATCODE NOT IN(SELECT AC.CUSTCATCODE FROM  A2CUSTCATEGORY AC) OR AB.CUSTCATCODE IS NULL;
/

--3.2
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2CUSTBRIS',5,sysdate,'MODIFY'
FROM A2CUSTBRIS AB
WHERE  AB.PHONE LIKE '%-%' OR AB.PHONE LIKE '% %';
/

--3.3
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2CUSTBRIS',6,sysdate,'SKIP'
FROM A2CUSTBRIS AB
WHERE (LENGTH(AB.PHONE)<10 OR LENGTH(AB.PHONE)>10) 
AND AB.PHONE NOT IN (SELECT PHONE
FROM A2CUSTBRIS
WHERE  PHONE LIKE '%-%' OR PHONE LIKE '% %');
/

--3.4
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2CUSTBRIS',7,sysdate,'MODIFY'
FROM A2CUSTBRIS AB
WHERE UPPER(AB.GENDER) NOT IN ('M','F') OR AB.GENDER IS NULL ;
/

--3.5.1

INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE,
POSTCODE, CITY, STATE, CUSTCATNAME)
SELECT DWCUSTSEQ.NEXTVAL,AB.CUSTID,NULL,AB.FNAME,AB.SNAME,UPPER(GENDER),AB.PHONE,AB.POSTCODE,AB.CITY,AB.STATE,AC.CUSTCATNAME
--(SELECT CUSTCATNAME FROM A2CUSTCATEGORY WHERE CUSTCATCODE IN (SELECT CUSTCATCODE FROM A2CUSTBRIS));
FROM A2CUSTBRIS AB, A2CUSTCATEGORY AC
WHERE AB.ROWID NOT IN (SELECT SOURCE_ROWID FROM A2ERROREVENT)
AND AB.CUSTCATCODE = AC.CUSTCATCODE;
/

--3.5.2
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE,
POSTCODE, CITY, STATE, CUSTCATNAME)
SELECT DWCUSTSEQ.NEXTVAL,AB.CUSTID,NULL,AB.FNAME,AB.SNAME,UPPER(GENDER),AB.PHONE,AB.POSTCODE,AB.CITY,AB.STATE,'UNKNOWN'
--(SELECT CUSTCATNAME FROM A2CUSTCATEGORY WHERE CUSTCATCODE IN (SELECT CUSTCATCODE FROM A2CUSTBRIS));
FROM A2CUSTBRIS AB
WHERE AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 4);
/

--3.5.3
INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE,
POSTCODE, CITY, STATE, CUSTCATNAME)
SELECT DWCUSTSEQ.NEXTVAL,AB.CUSTID,NULL,AB.FNAME,AB.SNAME,UPPER(GENDER),REPLACE(REPLACE(PHONE,'-',''),' ',''),AB.POSTCODE,AB.CITY,AB.STATE,AC.CUSTCATNAME
--(SELECT CUSTCATNAME FROM A2CUSTCATEGORY WHERE CUSTCATCODE IN (SELECT CUSTCATCODE FROM A2CUSTBRIS));
FROM A2CUSTBRIS AB, A2CUSTCATEGORY AC
WHERE AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 5)
AND AB.CUSTCATCODE = AC.CUSTCATCODE;
/

--3.5.4

INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE,
POSTCODE, CITY, STATE, CUSTCATNAME)
SELECT DWCUSTSEQ.NEXTVAL,AB.CUSTID,NULL,AB.FNAME,AB.SNAME,UPPER(GP.NEW_VALUE),PHONE,AB.POSTCODE,AB.CITY,AB.STATE,AC.CUSTCATNAME
--(SELECT CUSTCATNAME FROM A2CUSTCATEGORY WHERE CUSTCATCODE IN (SELECT CUSTCATCODE FROM A2CUSTBRIS));
FROM A2CUSTBRIS AB, GENDERSPELLING GP,A2CUSTCATEGORY AC
WHERE AB.CUSTCATCODE = AC.CUSTCATCODE 
AND( (GP.INVALID_VALUE IN (SELECT UPPER(GENDER) FROM A2CUSTBRIS) AND (GP.INVALID_VALUE = UPPER(AB.GENDER)))
OR (GP.NEW_VALUE IN(SELECT UPPER(GENDER) FROM A2CUSTBRIS) AND (GP.NEW_VALUE = UPPER(AB.GENDER))))
AND AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 7);
/

INSERT INTO DWCUST (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE,
POSTCODE, CITY, STATE, CUSTCATNAME)
SELECT DWCUSTSEQ.NEXTVAL,AB.CUSTID,NULL,AB.FNAME,AB.SNAME,'U',PHONE,AB.POSTCODE,AB.CITY,AB.STATE,AC.CUSTCATNAME
FROM A2CUSTBRIS AB,A2CUSTCATEGORY AC
WHERE AB.CUSTCATCODE = AC.CUSTCATCODE 
--AND GP.INVALID_VALUE = UPPER(AB.GENDER)
/*AND ((GP.INVALID_VALUE NOT IN(SELECT UPPER(AB.GENDER) FROM A2CUSTBRIS)
AND GP.INVALID_VALUE = UPPER(AB.GENDER))*/
AND (AB.GENDER IS NULL
OR UPPER(AB.GENDER) NOT IN (SELECT INVALID_VALUE FROM GENDERSPELLING))
AND AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 7);
/

---4.1

MERGE INTO DWCUST DC
USING A2CUSTMELB AC
ON (DC.FIRSTNAME = AC.FNAME AND DC.SURNAME = AC.SNAME AND DC.POSTCODE = AC.POSTCODE)
WHEN MATCHED THEN UPDATE SET DC.DWSOURCEIDMELB = AC.CUSTID
WHEN NOT MATCHED THEN
INSERT (DWCUSTID, DWSOURCEIDBRIS, DWSOURCEIDMELB, FIRSTNAME, SURNAME, GENDER, PHONE,
POSTCODE, CITY, STATE,CUSTCATNAME)
VALUES(DWCUSTSEQ.NEXTVAL,NULL,AC.CUSTID,AC.FNAME,AC.SNAME,AC.GENDER,AC.PHONE,AC.POSTCODE,AC.CITY,AC.STATE, 
(SELECT AA.CUSTCATNAME FROM A2CUSTCATEGORY AA WHERE CUSTCATCODE IN AC.CUSTCATCODE));
/

--5.1

insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEBRIS',8,sysdate,'SKIP'
FROM A2SALEBRIS 
WHERE PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD);
/

--5.2
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEBRIS',9,sysdate,'SKIP'
FROM A2SALEBRIS 
WHERE CUSTID NOT IN (SELECT DWSOURCEIDBRIS FROM DWCUST);
/

--5.3
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEBRIS',10,sysdate,'MODIFY'
FROM A2SALEBRIS 
WHERE SHIPDATE<SALEDATE;
/

--5.4
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEBRIS',11,sysdate,'MODIFY'
FROM A2SALEBRIS 
WHERE UNITPRICE IS NULL;
/

--5.5
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY,
SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
SELECT DWSALESEQ.NEXTVAL, DC.DWCUSTID,DP.DWPRODID,AB.SALEID,NULL,AB.QTY,DD.DATEKEY,DD.DATEKEY,AB.UNITPRICE
FROM A2SALEBRIS AB
    ,DWCUST DC 
    ,DWPROD DP
    ,DWDATE DD
WHERE AB.CUSTID = DC.DWSOURCEIDBRIS
AND AB.PRODID = DP.DWSOURCEID
AND AB.SALEDATE = DD.DATEVALUE
AND AB.ROWID NOT IN (SELECT SOURCE_ROWID FROM A2ERROREVENT);
/

--5.6
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY,
SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
SELECT DWSALESEQ.NEXTVAL, DC.DWCUSTID,DP.DWPRODID,AB.SALEID,NULL,AB.QTY,DD.DATEKEY,DD.DATEKEY+2,
AB.UNITPRICE
FROM A2SALEBRIS AB
    ,DWCUST DC 
    ,DWPROD DP
    ,DWDATE DD
WHERE AB.CUSTID = DC.DWSOURCEIDBRIS
AND AB.PRODID = DP.DWSOURCEID
AND AB.SALEDATE = DD.DATEVALUE
AND AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 10);
/

--5.7
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY,
SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
SELECT DWSALESEQ.NEXTVAL, DC.DWCUSTID,DP.DWPRODID,AB.SALEID,NULL,AB.QTY,DD.DATEKEY,DD.DATEKEY,(SELECT MAX(UNITPRICE) FROM A2SALEBRIS WHERE PRODID = DP.DWSOURCEID)
FROM A2SALEBRIS AB
    ,DWCUST DC 
    ,DWPROD DP
    ,DWDATE DD
WHERE AB.CUSTID = DC.DWSOURCEIDBRIS
AND AB.PRODID = DP.DWSOURCEID
AND AB.SALEDATE = DD.DATEVALUE
AND AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 11);
/

--6.1
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEMELB',12,sysdate,'SKIP'
FROM A2SALEMELB 
WHERE PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD);
/

--6.2
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEMELB',13,sysdate,'SKIP'
FROM A2SALEMELB 
WHERE CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST);
/

--6.3
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEMELB',14,sysdate,'MODIFY'
FROM A2SALEMELB 
WHERE SHIPDATE<SALEDATE;
/

--6.4
insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT   erroridseq.nextval,ROWID,'A2SALEMELB',15,sysdate,'MODIFY'
FROM A2SALEMELB 
WHERE UNITPRICE IS NULL;
/

insert into A2ERROREVENT (errorid,source_rowid,source_table,filterid,datetime,action) 
SELECT erroridseq.nextval,ROWID,'A2SALEMELB',16,sysdate,'SKIP'
FROM A2SALEMELB 
WHERE (PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD)
AND CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST))
OR(PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD)
AND (SHIPDATE<SALEDATE))
OR (PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD)
AND (UNITPRICE IS NULL))
OR (CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST)
AND (SHIPDATE<SALEDATE))
OR (CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST)
AND (UNITPRICE IS NULL))
OR ((SHIPDATE<SALEDATE) 
AND (UNITPRICE IS NULL))
OR (PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD)
AND CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST)
AND (SHIPDATE<SALEDATE))
OR (PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD)
AND CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST)
AND (UNITPRICE IS NULL))
OR (PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD)
AND (SHIPDATE<SALEDATE)
AND (UNITPRICE IS NULL))
OR ((SHIPDATE<SALEDATE)
AND CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST)
AND (UNITPRICE IS NULL))
OR (PRODID NOT IN (SELECT DWSOURCEID FROM DWPROD)
AND CUSTID NOT IN (SELECT DWSOURCEIDMELB FROM DWCUST)
AND SHIPDATE<SALEDATE
AND UNITPRICE IS NULL);
/

--6.5
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY,
SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
SELECT DWSALESEQ.NEXTVAL, DC.DWCUSTID,DP.DWPRODID,NULL,AB.SALEID,AB.QTY,DD.DATEKEY,DD.DATEKEY,AB.UNITPRICE
FROM A2SALEMELB AB
    ,DWCUST DC 
    ,DWPROD DP
    ,DWDATE DD
WHERE AB.CUSTID = DC.DWSOURCEIDMELB
AND AB.PRODID = DP.DWSOURCEID
AND AB.SALEDATE = DD.DATEVALUE
AND AB.ROWID NOT IN (SELECT SOURCE_ROWID FROM A2ERROREVENT);
/


--6.6
INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY,
SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
SELECT DWSALESEQ.NEXTVAL, DC.DWCUSTID,DP.DWPRODID,NULL,AB.SALEID,AB.QTY,DD.DATEKEY,DD.DATEKEY+2,
AB.UNITPRICE
FROM A2SALEMELB AB
    ,DWCUST DC 
    ,DWPROD DP
    ,DWDATE DD
WHERE AB.CUSTID = DC.DWSOURCEIDMELB
AND AB.PRODID = DP.DWSOURCEID
AND AB.SALEDATE = DD.DATEVALUE
AND AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 14)
AND AB.ROWID NOT IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 16);
/

--6.7

INSERT INTO DWSALE (DWSALEID, DWCUSTID, DWPRODID, DWSOURCEIDBRIS, DWSOURCEIDMELB, QTY,
SALE_DWDATEID, SHIP_DWDATEID, SALEPRICE)
SELECT DWSALESEQ.NEXTVAL,DC.DWCUSTID,DP.DWPRODID,NULL,AB.SALEID,AB.QTY,DD.DATEKEY,DD.DATEKEY,(SELECT MAX(UNITPRICE) FROM A2SALEMELB WHERE PRODID = DP.DWSOURCEID)
FROM A2SALEMELB AB
    ,DWCUST DC 
    ,DWPROD DP
    ,DWDATE DD
WHERE AB.CUSTID = DC.DWSOURCEIDMELB
AND AB.PRODID = DP.DWSOURCEIDS
AND AB.SALEDATE = DD.DATEVALUE
AND AB.ROWID IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 15)
AND AB.ROWID NOT IN (SELECT SOURCE_ROWID FROM A2ERROREVENT WHERE FILTERID = 16);
/


--8.1
SELECT DD.DAYNAME "WEEKDAY",SUM(DW.QTY*DW.UNITPRICE) "TOTAL SALES" 
FROM DWDATE DD, DWSALE DW
WHERE DD.DATEKEY = DW.SALE_DWDATEID
GROUP BY DD.DAYNAME
ORDER BY SUM(DW.SALEPRICE) DESC;
/

--8.2
SELECT DC.CUSTCATNAME "CUSTCATNAME",SUM(DW.QTY*DW.UNITPRICE) "TOTAL SALES"
FROM DWCUST DC,DWSALE DW
WHERE DC.DWCUSTID = DC.DWCUSTID
GROUP BY DC.CUSTCATNAME
ORDER BY SUM(DW.SALEPRICE);
/

--8.3
SELECT DP.PRODMANUNAME, SUM(DW.QTY)
FROM DWPROD DP, DWSALE DW
WHERE DP.DWPRODID = DW.DWPRODID 
GROUP BY DP.PRODMANUNAME
ORDER BY SUM(QTY) DESC;
/

--8.4
SELECT DC.DWCUSTID, DC.FIRSTNAME,DC.SURNAME,SUM(DW.SALEPRICE)
FROM DWCUST DC, DWSALE DW
WHERE DC.DWCUSTID = DW.DWCUSTID
GROUP BY DC.DWCUSTID, DC.FIRSTNAME,DC.SURNAME
ORDER BY SUM(DW.SALEPRICE) DESC
FETCH FIRST 10 ROWS ONLY;
/

--8.5
SELECT * FROM (SELECT DP.DWPRODID, DP.PRODNAME,SUM(DW.SALEPRICE)
FROM DWPROD DP, DWSALE DW
WHERE DP.DWPRODID = DW.DWPRODID
GROUP BY DP.DWPRODID, DP.PRODNAME
ORDER BY SUM(DW.SALEPRICE) DESC)
WHERE ROWNUM <=10 ORDER BY ROWNUM DESC;
/


--8.6

SELECT DC.STATE, DC.CITY,SUM(DW.SALEPRICE)
FROM DWCUST DC, DWSALE DW
WHERE DC.DWCUSTID = DW.DWCUSTID
GROUP BY DC.STATE, DC.CITY
ORDER BY SUM(DW.SALEPRICE);
/
